
-- visit https://github.com/rockerBOO/awesome-neovim

local Plug = vim.fn['plug#']

vim.call('plug#begin')
Plug('nvim-treesitter/nvim-treesitter')
Plug('sainnhe/gruvbox-material')
Plug('folke/which-key.nvim')
Plug('nvim-lualine/lualine.nvim')
Plug('nvim-tree/nvim-web-devicons')
Plug('goolord/alpha-nvim')
Plug('lewis6991/gitsigns.nvim')
Plug('windwp/nvim-autopairs')
Plug('numToStr/Comment.nvim')
Plug('norcalli/nvim-colorizer.lua')
Plug('nvim-telescope/telescope.nvim')
Plug('nvim-lua/plenary.nvim')
Plug('folke/noice.nvim')
Plug('MunifTanjim/nui.nvim')
Plug('nvim-neo-tree/neo-tree.nvim')
Plug('ThePrimeagen/vim-be-good')
Plug('mg979/vim-visual-multi')
Plug('neovim/nvim-lspconfig')
Plug('hrsh7th/cmp-nvim-lsp')
Plug('hrsh7th/nvim-cmp')
Plug('mason-org/mason.nvim')
Plug('mason-org/mason-lspconfig.nvim')
Plug('mfussenegger/nvim-jdtls')
Plug('ThePrimeagen/harpoon')
Plug('mbbill/undotree')
Plug('mfussenegger/nvim-dap')
Plug('echasnovski/mini.ai')
Plug('mrcjkb/rustaceanvim')
Plug('akinsho/toggleterm.nvim')
vim.call('plug#end')

require('config.options')
require('config.keybinds')

require('plugins.colorscheme')
require('plugins.lualine')
require('plugins.comment')
require('plugins.autopairs')
require('plugins.colorizer')
require('plugins.noice')
require('plugins.alpha')
require('plugins.neotree')
require('plugins.lsp')
require('plugins.harpoon')
require('plugins.vim-visual-multi')
require('plugins.mini-ai')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.toggleterm')
